name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: crazy-max/ghaction-setup-containerd@v1
      - uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          outputs: type=oci,dest=/tmp/image.tar
          tags: docker.pyrrha.gay/hellfire/web:latest
      - run: sudo ctr i import --base-name docker.io/user/app --digests --all-platforms /tmp/image.tar
      - run: sudo ctr --debug i push --user "${{ secrets.DOCKER_USERNAME }}:${{ secrets.DOCKER_PASSWORD }}" docker.pyrrha.gay/hellfire/web:latest
  deploy:
    runs-on: ubuntu-22.04
    needs: [ build ]
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo docker stop hellfire-web && docker rm hellfire-web
            sudo docker pull docker.pyrrha.gay/hellfire/web:latest
            sudo docker run -d -p 3000:3000 hellfire/web