name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - run: yarn install --immutable
      - run: yarn build
      - uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rav --delete"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.VPS_HOST }}
          REMOTE_USER: "ubuntu"
          TARGET: "/var/www/hellfire.pyrrha.dev/"
          EXCLUDE: "/dist/, /node_modules/"